export const ADD_DEFINITION = 'ADD_DEFINITION';
export const SEARCH_TERM = 'SEARCH_TERM';

export const TOGGLE_THUMBS_UP = 'TOGGLE_THUMBS_UP';
export const TOGGLE_THUMBS_DOWN = 'TOGGLE_THUMBS_DOWN';
export const TOGGLE_DISPLAY_SEARCH = 'TOGGLE_DISPLAY_SEARCH';
